version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - instance_volume:/app/KodeKloudTaskMan/instance
    environment:
      - FLASK_APP=KodeKloudTaskMan/app.py
      - FLASK_ENV=production
      - DATABASE=/app/instance/task_manager.sqlite
      - SECRET_KEY=${SECRET_KEY:-a_secure_random_key_for_development}
    command: >
      sh -c "cd /app && 
      mkdir -p /app/instance && 
      touch /app/instance/task_manager.sqlite && 
      chmod -R 777 /app/instance && 
      chown -R appuser:appuser /app/instance && 
      echo 'DROP TABLE IF EXISTS users; DROP TABLE IF EXISTS tasks; CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL); CREATE TABLE tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT, status TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by INTEGER NOT NULL, assigned_to INTEGER NOT NULL, FOREIGN KEY (created_by) REFERENCES users (id), FOREIGN KEY (assigned_to) REFERENCES users (id));' | sqlite3 /app/instance/task_manager.sqlite && 
      gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 2 KodeKloudTaskMan.app:app"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  instance_volume:
